name: cmeins
favicon: null
layout_spectrum: 0.3183575472794473
typography_spectrum: 0.8281745845451951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.006682612234726548
  lightness: 0.45353132928721607
  saturation: 0.9986006154213101
  rhythmicContrast: 0.8141000415198505
purpose: []
